apiVersion: v1
kind: Secret
metadata:
  name: nginx-tls
  labels:
    app: nginx
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-html
  labels:
    app: nginx
data:
  index.html: |
    <html>
      <head><title>Secure NGINX</title></head>
      <body><h1>nginx everything works fine 🔐</h1></body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 443
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
            - name: tls-volume
              mountPath: /etc/nginx/tls
              readOnly: true
      volumes:
        - name: html-volume
          configMap:
            name: nginx-custom-html
        - name: tls-volume
          secret:
            secretName: nginx-tls
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 443
      targetPort: 443
